### ISSUE TITLE
Custom Website Builder hosting questions

### ISSUE THREAD

**Issue by Herzogdb** [LaunchKit/LaunchKit#10]
1) If I want to remove some of the applications from the dashboard, which file would I be changing? (And in general how can I figure out which file to edit -- its not as simple as look at the html filename)
I'm looking in skit/LK/public/dashboard . For example, say I want to deactivate or remove the website builder.

2) Could you provide any suggestions on how to put this on a hosting platform and what type of hosting platform would be required? Would a regular linux host work where I currently have a regular html as well as a wordpress site?

3) The app requires you to create a user on your own instance. Is there a way to access the backend somewhere to manage/delete/edit users?

4) Some of the links point back to the LK blog. How do we find the right files to edit these links? For example, editing a website:
Website Settings
In order for other people to see your website, you'll need to set up a custom domain name. [Read instructions here](http://blog.launchkit.io/post/121139102739/custom-domain). Once you set things up, please remember that it can take up to 24 hours for your domain to activate.

**Comment by taylorhughes** [comment]
1) in general the lists of products in various places are controlled by (products.json)[https://github.com/LaunchKit/LaunchKit/blob/master/skit/lk/library/products/products.json]

2) there are a number of servers to run, so cohabitating with other processes on the same machine  would require some advanced configuration

3) you can access the machine directly by using `vagrant ssh` and then accessing the local database with psql. alternatively you could modify the `Vagrantfile` to expose the postgres port to your machine so you could use a local postgres GUI of some kind

4) just search the codebase for the link and it should be easy to find

**Comment by Herzogdb** [comment]
thx

**Comment by ArsalaBangash** [comment]
Any luck finding the blog? I still can't seem to locate it
