### ISSUE TITLE
install google app engine failed to find handler for .zip

### ISSUE THREAD

**Issue by junhohong** [LaunchKit/LaunchKit#15]
During vagrant --up provision, I get this error: 

TASK [lk-google-app-engine : install google app-engine] ************************
fatal: [default]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to find handler for \"/home/vagrant/google_appengine_1.9.27.zip\". Make sure the required command to extract the file is installed.", "stat": {"exists": false}}

It seems like my system cannot unzip the file properly. How can I fix this? I'm on OSX 10.11.3.

**Comment by taylorhughes** [comment]
Was there an error farther above about the "unzip" target that installs that requirement?

**Comment by junhohong** [comment]
There was not. The above was the only error.

**Comment by junhohong** [comment]
reinstalling LaunchKit and Virtual Machine seems to have fixed the problem.

**Comment by zhuhuihuihui** [comment]
@junhohong were you able to deploy it to GAE in the end?
