### ISSUE TITLE
Image uploads failing in browser for some reason

### ISSUE THREAD

**Issue by zzimbler** [LaunchKit/LaunchKit#16]
I'm not really a Python/Django person so forgive my ignorance here, but I can't get beyond the screen(see below) in the screenshot builder on the local dev env. The directions don't really mention any setup to GAE. Is there additional config that needs to happen to make that work properly?

<img width="1189" alt="screen shot 2016-08-04 at 11 56 46 pm" src="https://cloud.githubusercontent.com/assets/538636/17427608/2a530410-5a9f-11e6-9681-46aaeead4073.png">

**Comment by taylorhughes** [comment]
This typically works out of the box. Ansible configures a local instance of App Engine to enable uploads. Steps to diagnose:

1. see error message in Chrome console — include it here
2. does http://localhost:9103 redirect to launchkit.io? if not, local App Engine is not started
3. does http://localhost:9102 redirect to launchkit.io? if not, go proxy is not started

If you are technically savvy, you can ssh to the vm with `vagrant ssh` to see which processes are running. Run `ps aux |grep appengine` and `ps aux |grep proxy` to see if processes mentioned in 2. and 3. are running. You can also restart the machine using `vagrant halt` and then `vagrant up --provision` to see if that fixes it.

**Comment by zzimbler** [comment]
1. I don't see any message in chrome's console when I upload an image. I just see the loading spinner in perpetuity
2. localhost:9103 says locahost not working, I'd assume the local app engine is not starting
3. localhost:9102 redirects to launchkit.io

results for the `ps aux|grep appengine` is the attached image. I tried to restart a couple times but that didn't seem to do anything. I also had a friend of mine who is more familiar with python take a look at everything and he wasn't exactly sure what was going on either.

**Comment by taylorhughes** [comment]
Seems to be set up correctly. You'll need to inspect the upload request(s) in the browser to see what's happening. You can open the Chrome/Safari developer tools, visit the "Network" tab and select "XHR" to understand more about what's going on.

![screen shot 2016-08-05 at 10 42 06 am](https://cloud.githubusercontent.com/assets/907886/17445352/63dafa9e-5af9-11e6-8497-e8734409b352.png)

**Comment by taylorhughes** [comment]
Also can you try some other files and see if that works? Also try searching for an app's screenshots to see if that way works? Could be an issue with the file itself.

**Comment by zzimbler** [comment]
Unsure on the why, but I restarted it like 4 times and now it works. If I figure out the why I'll let you know.
