### ISSUE TITLE
Images broken in Preview

### ISSUE THREAD

**Issue by erickva** [LaunchKit/LaunchKit#21]
I configure my app in the App Website Builder and upload my screen shots, they appear nicely after the upload while I am still editing the app, but after I save or click preview, the images is broken. It points to: 
https://launchkit-io.imgix.net/devices/iPhone6White.png?w=750&h=1334&mark=http%3A%2F%2Flocalhost%3A9102%2F_ah%2Fimg%2FQoLYZQTcSPAYIgeiBJkwUQ%3D%3D&markh=970&markalign=center%2Cmiddle

I am running everything in localhost.
Icon and Logo images are fine though.

More info: the images that appear broken is the animation created from the screenshots!

**Comment by dipakthoke** [comment]
Facing  same issue !
can anyone help ?

**Comment by LuiggiMS** [comment]
Same problem here...

**Comment by dipakthoke** [comment]
Thank you very much @taylorhughes.
