### ISSUE TITLE
Make installation process simpler

### ISSUE THREAD

**Issue by Sparker0i** [LaunchKit/LaunchKit#32]
Hey there,

Great work on the product (as I've seen from the website). Unfortunately, the local installation process is a real pain for a simple user, who just wants to have a local version of screenshot builder working. I've tried `vagrant up --provision`, where earlier I used to get errors regarding python not found, and now with postgresql unable to start. 

Could be great if you could simplify the installation for a simple end-user.

Thanks and Regards.

**Comment by taylorhughes** [comment]
Please open bugs with specific issues you encounter that are reproducible. This is not consumer software and will never be. If you are looking for a hosted replacement for LaunchKit, try https://apptoolkit.io/

**Comment by dzungpv** [comment]
@taylorhughes https://apptoolkit.io/ yours? I try review monitor but it not work, stuck for 1 week with no review.
I try setup on my own but email not work, both on local Mac and real server Ubuntu Server 14.04 LTS. Is your version difference with original one? I post issues here #39
