### ISSUE TITLE
Setup LK on Amazone EC2

### ISSUE THREAD

**Issue by dzungpv** [LaunchKit/LaunchKit#38]
Anyone can make LK run on EC2? I want to use it on real server, not local.
But when i try to install VirtualBox on Centos 7, it failed with error: "Running VirtualBox in a Xen environment is not supported"

**Comment by chrisacameron** [comment]
try an Ubuntu AMI. I've got it mostly working in my environment using Ubuntu w/ VMWare

**Comment by dzungpv** [comment]
@chrisacameron So have you try with VirtualBox? VMWare require license too, also in the guide only have script for VirtualBox.

**Comment by chrisacameron** [comment]
@dzungpv yep I installed VirtualBox/ansible/docker/vagrant/etc on the Ubuntu machine.. you don't need VMware that's just my environment. You could probably use an AWS t2.micro instance.

**Comment by dzungpv** [comment]
Now i can install it on EC2 Ubuntu 14 without any virtual machine. Just install vagrant, ansible on my Mac and deploy it to EC2. But it cost me 3 hours with some customize.

**Comment by finalight** [comment]
are there any instructions to install on ec2? launckit requires virtualbox but ec2 doesn't support installation and launching of virtualbox
