### ISSUE TITLE
Which LaunchKit functionalities require Xcode dev tools?

### ISSUE THREAD

**Issue by acegreen** [LaunchKit/LaunchKit#5]
I intended to install LaunchKit on a DigitalOcean server but was hindered from doing so at the very first installation step. Xcode Command Line tools are only available on macOS. It would be great to understand which functionality requires this and if we can proceed without it?

**Comment by taylorhughes** [comment]
The guide is meant for OS X. On linux you just need whatever package(s) include build tools like `cc`. Skip the step and try to install ansible. If it works, you should be fine.

**Comment by taylorhughes** [comment]
Updated README

**Comment by acegreen** [comment]
@taylorhughes any way we can run things without vagrant? I tried to install vagrant on my server but I don't think thats how its suppose to be used. Something like npm support would be great. Parse-Server deploys it really well

**Comment by taylorhughes** [comment]
No, our servers are written in three different languages and have requirements spread between apt, pypi and npm. Inside vagrant (using ansible) we automatically spawn a dozen different programs to make the service work. Supporting npm alone is not remotely possible.

You're welcome to dig into the ansible configuration and spawn the services listed there yourself without a virtualization environment. The python requirements are listed in `requirements.txt`, the npm requirements are listed in `skit/package.json`, and inside each upstart configuration file you can find the raw commands for starting all the necessary servers.

**Comment by acegreen** [comment]
Ok that's perfect.

**Comment by 5280advantage** [comment]
No success with this?
