### ISSUE TITLE
Last Step (5) Failed - HANDLER [redis : restart redis]

### ISSUE THREAD

**Issue by Herzogdb** [LaunchKit/LaunchKit#7]
I got all the way to the last step 5 and it looks like everything worked except this.
It still worked.

RUNNING HANDLER [redis : restart redis] ****************************************
fatal: [default]: FAILED! => {"changed": false, "failed": true, "msg": "no service or tool found for: redis"}
...ignoring

**Comment by acegreen** [comment]
Last step is 6. did you cd LaunchKit?

**Comment by taylorhughes** [comment]
I recall possibly seeing something similar, we'll have to see if anybody else runs into the same problem. What platform were you running this on @Herzogdb?

**Comment by taylorhughes** [comment]
Actually, I believe this should fix it https://github.com/LaunchKit/LaunchKit/commit/a29e42ed06a0a5827773a1ade6dcdcbb95d506fb

**Comment by Herzogdb** [comment]
Thanks. I'm running MacBook Air OS 10.11.6 (15G31)
