### ISSUE TITLE
vagrant up --provision stuck on 'Booting VM...'

### ISSUE THREAD

**Issue by acegreen** [LaunchKit/LaunchKit#8]
Fought my way through the steps but can't seem to proceed past the booting VM. I gave it sufficient time of course. Is this a memory size issue? 

I tried reducing the memory size so that both fit on a 1GB server but still no luck. 

**Server Info: 1 GB Memory / 20 GB Disk - Ubuntu 16.04.1 x64
vboxmanage --version : 5.0.26r108824
Vagrant 1.8.1**

<img width="561" alt="screen shot 2016-07-28 at 9 28 55 pm" src="https://cloud.githubusercontent.com/assets/10794609/17234861/89f735a2-550a-11e6-9702-49b9d641c2bb.png">

**Comment by taylorhughes** [comment]
What type of system are you booting this VM on?

**Comment by acegreen** [comment]
@taylorhughes was updating my description as you wrote your comment (see update)

**Comment by taylorhughes** [comment]
Is this a virtual machine hosted somewhere or a physical piece of hardware in your control?

**Comment by acegreen** [comment]
digital ocean droplet

**Comment by taylorhughes** [comment]
Rather than attempting to start a virtual machine inside of another virtual machine, I would suggest setting up digitalocean as your vagrant "provider". This will create a new digitalocean machine for you. You will need to modify the Vagrantfile with your own custom configuration.

https://www.digitalocean.com/community/tutorials/how-to-use-digitalocean-as-your-provider-in-vagrant-on-an-ubuntu-12-10-vps

**Comment by acegreen** [comment]
Ahh thats what I was doing before coming across the fact that Launchkit included the info already. Let me take a jab at it

**Comment by taylorhughes** [comment]
This will require some extra work from you to get it functional. Please do not file bugs about it once you start straying from the default vagrant configuration I have provided here.

**Comment by acegreen** [comment]
Yea of course. While we are on this topic. which of the providers do I replace?

My config was as such:

```
  config.vm.box = "digital_ocean"
  config.ssh.private_key_path = "~/.ssh/id_rsa"
  config.vm.provider :digital_ocean do |provider|
    provider.client_id = "450768345d88bdd03431a839b0b29c2dbd7380465d5fcd0969ddee31a1a188aa"
    provider.api_key = "4a51a171da59c8c9e11ecd57978052913d0b630e0433d0bad1b8ea56b3390ead"
    provider.image = "Ubuntu 16.04.1 x64"
    provider.region = "Toronto 1"
  end
```

**Comment by taylorhughes** [comment]
I'm not exactly sure but you will likely have to pass --provider= when calling vagrant up. Also I would suggest invalidating that access key pair as it has been shared publicly in this ticket 






On Thu, Jul 28, 2016 at 6:44 PM -0700, "Ace Green" <notifications@github.com> wrote:












Yea of course. While we are on this topic. which of the providers do I replace?



My config was as such:

  config.vm.box = "digital_ocean"
  config.ssh.private_key_path = "~/.ssh/id_rsa"
  config.vm.provider :digital_ocean do |provider|
    provider.client_id = "450768345d88bdd03431a839b0b29c2dbd7380465d5fcd0969ddee31a1a188aa"
    provider.api_key = "4a51a171da59c8c9e11ecd57978052913d0b630e0433d0bad1b8ea56b3390ead"
    provider.image = "Ubuntu 16.04.1 x64"
    provider.region = "Toronto 1"
  end

**Comment by acegreen** [comment]
Only your reply shows it :P
